Repository hashicorp/packer-plugin-amazon, pull requests merged in 2021-05, with the labels that each got.

#78 Update import.mdx
  docs/post-processors/import.mdx
Labels: docs

#83 Added support for fleet_tags / fleet_tag
  builder/common/run_config.go
  builder/common/step_run_spot_instance.go
  builder/common/step_run_spot_instance_test.go
  builder/ebs/builder.go
  builder/ebs/builder.hcl2spec.go
  builder/ebssurrogate/builder.go
  builder/ebssurrogate/builder.hcl2spec.go
  builder/ebsvolume/builder.go
  builder/ebsvolume/builder.hcl2spec.go
  builder/instance/builder.go
  builder/instance/builder.hcl2spec.go
  docs-partials/builder/common/RunConfig-not-required.mdx
  docs-partials/builders/aws-spot-docs.mdx
Labels: enhancement

#86 goreleaser - point to the correct version package
  .goreleaser.yml
Labels: bug
