Repository hashicorp/packer-plugin-amazon, pull requests merged in 2023-04, with the labels that each got.

#363 Add support for KMS keys in the aws-cn partition
  builder/common/ami_config.go
  builder/common/ami_config_test.go
Labels: enhancement

#364 Support explicit public ip on default vpc
  builder/common/step_network_info.go
  builder/common/step_run_source_instance.go
  builder/common/step_run_spot_instance.go
  builder/ebs/builder.go
  builder/ebs/builder_acc_test.go
  builder/ebssurrogate/builder.go
  builder/ebsvolume/builder.go
  builder/instance/builder.go
Labels: bug

#365 .gitignore: ignore crash.log
  .gitignore
Labels: tech-debt
