Repository hashicorp/packer-plugin-amazon, pull requests merged in 2024-05, with the labels that each got.

#480 Bump required actions to address Node.js 16 deprecation issue
  .github/actions/build-and-persist-plugin-binary/action.yml
  .github/workflows/acceptance-tests.yml
  .github/workflows/go-validate.yml
  .github/workflows/jira.yml
  .github/workflows/release.yml
Labels: dependencies, security

#482 common: move deprecation_time to AMIConfig
  .web-docs/components/builder/chroot/README.md
  .web-docs/components/builder/ebs/README.md
  .web-docs/components/builder/ebssurrogate/README.md
  .web-docs/components/builder/instance/README.md
  builder/chroot/builder.go
  builder/chroot/builder.hcl2spec.go
  builder/common/ami_config.go
  builder/common/step_enable_deprecation.go
  builder/ebs/builder.go
  builder/ebs/builder.hcl2spec.go
  builder/ebssurrogate/builder.go
  builder/ebssurrogate/builder.hcl2spec.go
  builder/ebssurrogate/builder_acc_test.go
  builder/instance/builder.go
  builder/instance/builder.hcl2spec.go
  docs-partials/builder/common/AMIConfig-not-required.mdx
  docs-partials/builder/ebs/Config-not-required.mdx
Labels: enhancement

#483 common: validate capacity reservation options
  builder/common/run_config.go
  builder/common/run_config_test.go
Labels: bug
